version: "3.4"
services:
  node-roles-app:
    container_name: dc-roles-app
    build: .
    ports:
      - 8092:3000
  db:
    image: postgres
    environment:
        POSTGRES_PASSWORD: '123456'
        POSTGRES_USER: 'postgres'
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
